# Generated by Django 2.2 on 2019-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_description', models.TextField()),
                ('shop_location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SH_Shop_Info',
            },
        ),
    ]
