# Generated by Django 2.2 on 2019-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'SH_Branch',
            },
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name_plural': 'Shop'},
        ),
    ]
