# Generated by Django 2.2 on 2019-04-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190420_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('NODE', 'NODE'), ('LEAF', 'LEAF')], default='NODE', max_length=5)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('category_link_name', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Branch')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'SH_Category',
            },
        ),
    ]
