# Generated by Django 2.2 on 2019-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190421_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/logos'),
        ),
    ]
