# Generated by Django 2.2 on 2019-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190430_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
    ]
