# Generated by Django 2.2 on 2019-04-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190430_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='currency_iso',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_link', models.TextField()),
                ('product_image_main', models.ImageField(upload_to='photos/products')),
                ('product_image_one', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('product_image_two', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('product_image_three', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('product_image_four', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('product_image_five', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('product_description', models.TextField()),
                ('has_size', models.BooleanField(default=False)),
                ('size_xs', models.BooleanField(default=False)),
                ('size_s', models.BooleanField(default=False)),
                ('size_m', models.BooleanField(default=False)),
                ('size_l', models.BooleanField(default=False)),
                ('size_xl', models.BooleanField(default=False)),
                ('size_xxl', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('free_shipping', models.BooleanField(default=False)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Categories')),
                ('subcategories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.SubCategories')),
            ],
        ),
    ]
