# Generated by Django 2.2 on 2019-04-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190430_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='currency_iso',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
