# Generated by Django 2.2 on 2019-04-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20190430_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='currency_iso',
        ),
    ]
