# Generated by Django 2.2 on 2019-04-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_shop_currency_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency_iso',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
