# Generated by Django 2.2 on 2019-05-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190430_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategories',
            new_name='subcategory',
        ),
    ]
