# Generated by Django 2.2 on 2019-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20190430_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
